# THIS FILE CONTAINS ALL SECRETS REQUIRED TO RUN THE CLUSTER'S PLATFORM

# DataDog Operator/Agent Secret

apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    datadog-api-key: "FOO"
    datadog-app-key: "BAR"
