apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datadog-operator
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./platform/demo
  prune: true
  wait: true
  timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: datadog-agent
# spec:
#   dependsOn:
#     - name: datadog-operator
#   interval: 15m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./platform/datadog-agent/sss
#   prune: true