apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 2h
  url: https://charts.containeroo.ch

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=default}
  serviceAccountName: kustomize-controller
  chart:
    spec:
      chart: local-path-provisioner
      interval: 1h
      version: 0.2.13
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
  interval: 1h
  values:
    storageClass:
      defaultClass: true