apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./platform/grafana/local
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: grafana
    substituteFrom:
      - kind: ConfigMap
        name: platform-namespace-vars
        # Use this ConfigMap if it exists, but proceed if it doesn't.
        optional: true
      - kind: Secret
        name: cluster-secrets
        optional: false