# THIS FILE CONTAINS ALL SECRETS REQUIRED TO RUN THE CLUSTER'S PLATFORM
# PATCH THEM IN EACH CLUSTER INSTANCE WITH THE PROPER VALUES!

apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    grafana-metrics-user: ""
    grafana-metrics-pass: ""
    grafana-logs-user: ""
    grafana-logs-pass: ""