# THIS FILE CONTAINS ALL SECRETS REQUIRED TO RUN THE CLUSTER'S PLATFORM

apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    # No worries, these secrets used to be valid but not anymore

    # Grafana uses numbered IDs, but in some parts it is expecting a string
    # We are escaping the string as otherwise the templating is formatting them as a number for unknown reasons
    grafana_metrics_user: "\"1073042\""
    grafana_metrics_pass: "glc_eyJvIjoiODkyNjc5IiwibiI6Ims4c2hvbWV0b2tlbiIsImsiOiIyNTdZcjFsN2NoR1A2Mll2Y2IyODRDaHIiLCJtIjp7InIiOiJwcm9kLWV1LXdlc3QtMiJ9fQ=="
    grafana_logs_user: "\"637291\""
    grafana_logs_pass: "glc_eyJvIjoiODkyNjc5IiwibiI6Ims4c2hvbWV0b2tlbiIsImsiOiIyNTdZcjFsN2NoR1A2Mll2Y2IyODRDaHIiLCJtIjp7InIiOiJwcm9kLWV1LXdlc3QtMiJ9fQ=="
