apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 2h
  url: https://kubernetes-sigs.github.io/external-dns/

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=default}
  serviceAccountName: kustomize-controller
  chart:
    spec:
      chart: external-dns
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: '1.12.2'
  interval: 15m
  values:
    provider: azure
    logFormat: json
    serviceAccount:
      annotations:
        azure.workload.identity/client-id: ${APPLICATION_OR_USER_ASSIGNED_IDENTITY_TENANT_ID}