apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: hostpath-provisioner
  namespace: flux-system
spec:
  interval: 2h
  url: https://charts.rimusz.net

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hostpath-provisioner
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=default}
  serviceAccountName: kustomize-controller
  chart:
    spec:
      chart: hostpath-provisioner
      interval: 1h
      version: 0.2.13
      sourceRef:
        kind: HelmRepository
        name: hostpath-provisioner
  interval: 1h
  values:
    image:
      repository: "rancher/local-path-provisioner"
      tag: "v0.0.24-amd64"
    nodeHostPath: "/opt/hotpath"
    storageClass:
      name: default