apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  type: oci
  interval: 4h
  url: oci://registry-1.docker.io/bitnamicharts

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  targetNamespace: metallb
  serviceAccountName: kustomize-controller
  chart:
    spec:
      chart: metallb
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: '4.4.2'
  interval: 15m
  values: {}
