apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 4h
  url: https://helm.datadoghq.com

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog-operator
  namespace: datadog
spec:
  targetNamespace: datadog
  serviceAccountName: kustomize-controller
  chart:
    spec:
      chart: datadog-operator
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: datadog
      version: '1.0.*'
  interval: 15m
  values:
    apiKeyExistingSecret: datadog-secret
    appKeyExistingSecret: datadog-secret
    site: datadoghq.eu
    datadogMonitor:
      enabled: true
    datadogCRDs:
      migration:
        datadogAgents:
          version: v2alpha1 # Temporal config to tell the operator to use v2alpha1 as the ddAgent CRD
          useCertManager: false
          conversionWebhook:
            enabled: false
    env: # Datadog is not honoring the `site` value (https://github.com/DataDog/datadog-operator/issues/623)
      - name: DD_URL
        value: "https://api.datadoghq.eu"

    watchNamespaces:
     - "" # Watch all namespaces for CRDs
