apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./platform/ingress-nginx/sss
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: ingress-nginx
    substituteFrom:
      - kind: ConfigMap
        name: platform-namespace-vars
        # Use this ConfigMap if it exists, but proceed if it doesn't.
        optional: true