apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: azure-workload-identity
  namespace: flux-system
spec:
  interval: 2h
  url: https://azure.github.io/azure-workload-identity/charts

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-workload-identity
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=default}
  serviceAccountName: kustomize-controller
  chart:
    spec:
      chart: workload-identity-webhook
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: azure-workload-identity
      version: '1.0.2'
  interval: 15m
  values:
    azureTenantID: ${azure_workload_identity_azure_tenant_id}