apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    spec:
      tolerations:
        - effect: NoSchedule
          key: CriticalAddonsOnly
          operator: Equal
          value: "true"
