apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 2h
  url: https://charts.jetstack.io

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      interval: 1h
      version: v1.11.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  interval: 1h
  values:
    installCRDs: true